app:
  command: "go run main.go"
  port: 3000
services:
  postgres:
    enabled: true
  redis:
    enabled: false
  mailpit:
    enabled: false
  minio:
    enabled: false
commands:
  install: go mod download
  dev: go run main.go
  build: go build -o app main.go
