package compose

import (
	"bytes"
	"devdock/internal/config"
	"devdock/internal/services"
	"devdock/internal/utils"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const Header = `# Generated by DevDock from .devdock.yml
# devdock version: 0.1.0
# Manual edits to this file may be overwritten. Edit .devdock.yml instead.
`

type Compose struct {
	Name     string                      `yaml:"name"`
	Services map[string]services.Service `yaml:"services"`
	Volumes  map[string]any              `yaml:"volumes,omitempty"`
	Networks map[string]any              `yaml:"networks,omitempty"`
}

func IsDevDockOwned(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(b), "Generated by DevDock")
}

func Generate(projectDir string, cfg *config.Config) error {
	projName := utils.NormalizeProjectName(cfg.Project.Name)

	comp := Compose{
		Name:     projName,
		Services: make(map[string]services.Service),
		Volumes:  make(map[string]any),
		Networks: make(map[string]any),
	}

	comp.Networks["devdock_network"] = map[string]any{
		"driver": "bridge",
	}

	if cfg.Services.Postgres != nil && cfg.Services.Postgres.Enabled {
		comp.Services["postgres"] = services.BuildPostgres(projName, *cfg.Services.Postgres)
		comp.Volumes[fmt.Sprintf("devdock_%s_postgres_data", projName)] = nil
	}

	if cfg.Services.MySQL != nil && cfg.Services.MySQL.Enabled {
		comp.Services["mysql"] = services.BuildMySQL(projName, *cfg.Services.MySQL)
		comp.Volumes[fmt.Sprintf("devdock_%s_mysql_data", projName)] = nil
	}

	if cfg.Services.Redis != nil && cfg.Services.Redis.Enabled {
		comp.Services["redis"] = services.BuildRedis(projName, *cfg.Services.Redis)
		comp.Volumes[fmt.Sprintf("devdock_%s_redis_data", projName)] = nil
	}

	var buf bytes.Buffer
	buf.WriteString(Header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(comp); err != nil {
		return err
	}
	enc.Close()

	composePath := filepath.Join(projectDir, "compose.yml")
	tmpPath := composePath + ".tmp"

	if err := os.WriteFile(tmpPath, buf.Bytes(), 0644); err != nil {
		return err
	}
	
	return os.Rename(tmpPath, composePath)
}
